/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as ApiPublicPushGithubRouteImport } from './routes/api/public/push-github'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushGithubRoute = ApiPublicPushGithubRouteImport.update({
  id: '/api/public/push-github',
  path: '/api/public/push-github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/produit/$id': typeof ProduitIdRoute
  '/api/public/push-github': typeof ApiPublicPushGithubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/produit/$id': typeof ProduitIdRoute
  '/api/public/push-github': typeof ApiPublicPushGithubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/produit/$id': typeof ProduitIdRoute
  '/api/public/push-github': typeof ApiPublicPushGithubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/produit/$id' | '/api/public/push-github'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/produit/$id' | '/api/public/push-github'
  id: '__root__' | '/' | '/admin' | '/produit/$id' | '/api/public/push-github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProduitIdRoute: typeof ProduitIdRoute
  ApiPublicPushGithubRoute: typeof ApiPublicPushGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-github': {
      id: '/api/public/push-github'
      path: '/api/public/push-github'
      fullPath: '/api/public/push-github'
      preLoaderRoute: typeof ApiPublicPushGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProduitIdRoute: ProduitIdRoute,
  ApiPublicPushGithubRoute: ApiPublicPushGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
